### ISSUE TITLE
UBP-X800M2

### ISSUE THREAD

**Issue by ddetton** [kenragan/UBPControl#1]
Just tried this module with a Sony UBP-X800M2 and got an error that the target machine actively refused it.  MAC and IP are valid.  I know that you don't advertise that it works with the UBP-x800M2 but just thought I'd let you know.

**Comment by kenragan** [comment]
I've not tried it with the UBP-x800M2, but am going to be looking at it in the future.  Would you mind sharing which Crestron processor you're using and if its a CP3N/PRO3 whether the control subnet is in use?

**Comment by ddetton** [comment]
MC3 running most recent firmware.  Either 1.502 or 1.503.

**Comment by dragoncleo** [comment]
Same to me. MC3 last firmware with UBP-X800M2

425. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # Module S-7.3.1 : SonyUBPController at line 38: Unhandled Exception: System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Sockets.Socket.ConnectNoCheck(EndPoint remoteEP)
   at Sy426. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # stem.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Crestron.SimplSharp.Net.Connection.DataSocketConnect(EndPoint aEndPoint)
   at Crestron.SimplSharp.Net.Connection.Connect(IPAddress aIPAddress, Int32 aPort)
   at Crestron.SimplSharp.Net.Client.G427. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # etConnection(IPAddress aHost, Int32 aPort)
   at Crestron.SimplSharp.Net.Client.Connect(IPAddress aHost, Int32 aPort)
   at Crestron.SimplSharp.Net.Client.Connect(String aHost, Int32 aPort)
   at Crestron.SimplSharp.Net.Http.HttpClient.GetHttpConnectio428. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # n(Boolean aSecure, String aHost, Int32 aPort)
   at Crestron.SimplSharp.Net.Http.HttpClient.TryDispatch(HttpClientRequest aRequest)
   at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch(HttpClientRequest aRequest)
   at Crestron.SimplSharp.Net.Http.Ht429. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # tpClient.GetResponse(String aUrl)
   at Crestron.SimplSharp.Net.Http.HttpClient.Get(String aUrl, Encoding aEncoding)
   at Crestron.SimplSharp.Net.Http.HttpClient.Get(String aUrl)
   at SonyUBPControl.PlayerControl.RegisterInit()
   at UserModule_SONY430. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # UBPCONTROLLER.UserModuleClass_SONYUBPCONTROLLER.REGISTER_OnPush_0(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.o()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)
   at Amib.Threadi431. Error: splusmanagerapp.exe [App 1] # 2023-05-15 11:52:37  # ng.SmartThreadPool.p()

**Comment by kenragan** [comment]
At this time, my testing on the UBP-X800M2 (running port scan and trying the different endpoints it offers) has revealed that it does not support IP control.  IR and CEC are currently the only way to control it that I've found.
